#### Histograma

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
#local do arquivo base de dados
file_path = 'C:/Users/Elvis/Documents/Estudo/UDEMY/Formação Cientista de Dados/12-2021/13.Prática em Python/dados/trees.csv'

In [3]:
#lendo a base de dados
df_trees = pd.read_csv(file_path)

In [7]:
# ver as qtd de linhas e colunas
df_trees.shape

(31, 3)

In [5]:
#dados
df_trees.head()

Girth  Height  Volume
0    8.3      70    10.3
1    8.6      65    10.3
2    8.8      63    10.2
3   10.5      72    16.4
4   10.7      81    18.8

In [ ]:
# Criação do histograma, considerando somente o segundo atributo (Height) da base de dados e com duas divisões (bins)
# A variável 'h' armazena as faixas de valores de Height


In [8]:
h = np.histogram(df_trees.iloc[:, 1], bins=6)
h

(array([4, 2, 5, 7, 9, 4], dtype=int64),
 array([63., 67., 71., 75., 79., 83., 87.]))

(array([4, 2, 5, 7, 9, 4], dtype=int64),         => Eixo X

 array([63., 67., 71., 75., 79., 83., 87.]))     => Eixo Y

In [ ]:
# Visualização do histograma com 6 divisões (bins)
plt.hist(df_trees.iloc[:, 1], bins=6)
plt.title('Árvores')
plt.ylabel('Frequência')
plt.xlabel('Altura')

Text(0.5, 0, 'Altura')